/**
 * Seed the PulseGen score feed for integration testing and demos.
 *
 * Exercises the real delivery path end to end — CSV parse → batch validation →
 * provenance record → score rows → automatic SCOUT badge assignment — so the
 * `pulsegen` channel is under test without a live endpoint.
 *
 * Scores resolve as `source: pulsegen`, which is accurate: that is the channel
 * they arrived through. `supplier` records who actually sent them and defaults
 * to a label that does not claim to be PathPulse.ai, because that field is a
 * factual claim about origin. Pass `--supplier` only when a real party really
 * did deliver the data.
 *
 * Idempotent: re-running re-delivers the batch and leaves badges that already
 * match their score untouched.
 *
 *   pnpm --filter @pathpulse/backend exec tsx scripts/seed-score-feed.ts
 *   pnpm --filter @pathpulse/backend exec tsx scripts/seed-score-feed.ts --file scores.csv
 *   pnpm --filter @pathpulse/backend exec tsx scripts/seed-score-feed.ts \
 *     --file client-export.csv --supplier "PathPulse.ai" --source-ref pulsegen-2026-09-20.csv
 */
import { readFileSync } from 'node:fs';
import { migrate, closeDb } from '../src/db/client.js';
import { hashPayload, saveImport } from '../src/services/scoreStore.js';
import { parseScoreCsv, validateScoreBatch, resolveScore } from '../src/services/pulsegen.js';
import { getManagedWallet, provisionManagedWallet } from '../src/stellar/managed.js';
import { assignTierForDriver, getOnchainTier, scoreToTier } from '../src/stellar/scout.js';

const DEFAULT_SUPPLIER = 'EngxLab — sample data, not PulseGen output';

/** Spans all three tiers so a settlement demo shows 1.0x / 1.2x / 1.5x. */
const SAMPLE_CSV = [
  'driver_id,score,scored_at',
  'drv-pulsegen-demo-002,0.2140,2026-09-18T09:00:00Z',
  'drv-pulsegen-demo-003,0.6480,2026-09-18T09:00:00Z',
  'drv-pulsegen-demo-006,0.9120,2026-09-18T09:00:00Z',
].join('\n');

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 ? undefined : process.argv[i + 1];
}

async function main(): Promise<void> {
  const file = arg('file');
  const csv = file ? readFileSync(file, 'utf8') : SAMPLE_CSV;
  const supplier = arg('supplier') ?? DEFAULT_SUPPLIER;
  const sourceRef = arg('source-ref') ?? (file ?? 'built-in sample cohort');

  if (!file && arg('supplier')) {
    throw new Error('--supplier names who delivered a real file; it cannot describe the built-in sample');
  }

  await migrate();

  const { scores } = validateScoreBatch(parseScoreCsv(csv));
  const record = await saveImport(
    {
      supplier,
      sourceRef,
      notes: file ? undefined : 'Generated by seed-score-feed.ts for integration testing.',
      importedBy: 'seed-script',
      receivedAt: new Date().toISOString(),
      payloadSha256: hashPayload(csv),
    },
    scores,
  );

  console.log('\n── delivery recorded ──');
  console.log({
    importId: record.id,
    supplier: record.supplier,
    sourceRef: record.sourceRef,
    scoreCount: record.scoreCount,
    payloadSha256: record.payloadSha256,
  });
  if (supplier === DEFAULT_SUPPLIER) {
    console.log('supplier is the sample label — pass --file and --supplier for a real delivery.');
  }

  console.log('\n── assigning badges from the delivered scores ──');
  for (const s of scores) {
    const wallet =
      (await getManagedWallet(s.driverId)) ?? (await provisionManagedWallet(s.driverId));
    const validation = await resolveScore(s.driverId);
    const expected = scoreToTier(validation.score);
    const current = await getOnchainTier(wallet.address);

    if (current.tier === expected) {
      console.log(
        `${s.driverId}  score ${validation.score.toFixed(4)} (${validation.source})  → SCOUT${expected}  already held`,
      );
      continue;
    }

    const assignment = await assignTierForDriver(s.driverId);
    console.log(
      `${s.driverId}  score ${validation.score.toFixed(4)} (${validation.source})  → SCOUT${assignment.tier} @ ${assignment.multiplier}x  tx ${assignment.txHash}`,
    );
  }

  console.log('\nFeed seeded. The SCOUT console now shows these scores and their provenance.');
  await closeDb();
}

main().catch(async (e) => {
  console.error(e);
  await closeDb();
  process.exit(1);
});
